= ModuleToken
/ ProgramIdToken
/ ExportToken
/ DataToken
/ ProcedureToken
/ DivisionToken
/ WorkingStorageToken
/ LinkageToken
/ SectionToken
/ Comp2Token
/ Comp4Token
/ DisplayToken
/ AnyToken
/ UsingToken
/ ReturningToken
/ PicToken
/ ValueToken
/ ByToken
/ ReferenceToken
/ ContentToken
/ CallToken
/ GobackToken
/ EndCallToken
/ EndDisplayToken
/ EndProgramToken
